### ISSUE TITLE
Deleting files

### ISSUE THREAD

**Issue by Kertrix** [DaBluLite/lunar-client-linux-installer#3]
I ran lunar-client-installer to uninstall lunar clienbt and it deleted My Desktop folder

**Comment by DaBluLite** [comment]
I actually experienced this problem while making it. I'm still trying to find how it ends up doing that.

**Comment by DaBluLite** [comment]
I made some changes to the uninstall script, hoping that it fixed it. I will test it a few times tomorrow.

**Comment by Kertrix** [comment]
Thanks
